version: '2'
services:
  nginx:
    image: paloit/nginx-fr:1.13.2
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
      - ./global.conf:/etc/nginx/conf.d/global.conf

  dockergen:
    image: paloit/docker-gen-fr:0.7.3
    command: -notify-sighup nginx-proxy -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./app.tmpl:/etc/docker-gen/templates/nginx.tmpl